"""initial schema

Revision ID: 9e733c929b4e
Revises:
Create Date: 2026-03-09 16:56:38.827333

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9e733c929b4e"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "category_groups",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "persons",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("adjustment_account", sa.String(), server_default="", nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "reconciliation_periods",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("month", sa.Integer(), nullable=False),
        sa.Column("is_finalized", sa.Boolean(), nullable=False),
        sa.Column("finalized_at", sa.String(), nullable=True),
        sa.Column("notes", sa.String(), nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("year", "month"),
    )
    op.create_table(
        "category_group_budgets",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("group_id", sa.String(), nullable=False),
        sa.Column("monthly_amount", sa.String(), nullable=False),
        sa.Column("effective_from", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["group_id"], ["category_groups.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("group_id", "effective_from"),
    )
    op.create_table(
        "category_mappings",
        sa.Column("category", sa.String(), nullable=False),
        sa.Column("group_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["group_id"], ["category_groups.id"]),
        sa.PrimaryKeyConstraint("category"),
    )
    op.create_table(
        "uploads",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("person_id", sa.String(), nullable=False),
        sa.Column("filename", sa.String(), nullable=False),
        sa.Column("uploaded_at", sa.String(), nullable=False),
        sa.Column("period_year", sa.Integer(), nullable=False),
        sa.Column("period_month", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["person_id"], ["persons.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "transactions",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("upload_id", sa.String(), nullable=False),
        sa.Column("date", sa.String(), nullable=False),
        sa.Column("merchant", sa.String(), nullable=False),
        sa.Column("category", sa.String(), nullable=False),
        sa.Column("account", sa.String(), nullable=False),
        sa.Column("original_statement", sa.String(), nullable=False),
        sa.Column("notes", sa.String(), nullable=False),
        sa.Column("amount", sa.String(), nullable=False),
        sa.Column("tags_json", sa.String(), nullable=False),
        sa.Column("is_shared", sa.Boolean(), nullable=False),
        sa.Column("payer_person_id", sa.String(), nullable=False),
        sa.Column("payer_percentage", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["payer_person_id"], ["persons.id"]),
        sa.ForeignKeyConstraint(["upload_id"], ["uploads.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_transactions_shared_date",
        "transactions",
        ["is_shared", "date"],
        unique=False,
    )
    op.create_index(
        "ix_transactions_upload_id", "transactions", ["upload_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_transactions_upload_id", table_name="transactions")
    op.drop_index("ix_transactions_shared_date", table_name="transactions")
    op.drop_table("transactions")
    op.drop_table("uploads")
    op.drop_table("category_mappings")
    op.drop_table("category_group_budgets")
    op.drop_table("reconciliation_periods")
    op.drop_table("persons")
    op.drop_table("category_groups")
    # ### end Alembic commands ###
