from typing import Protocol
from uuid import UUID

from src.domain.entities.category import Category


class CategoryRepositoryProtocol(Protocol):
    async def get_by_name(self, name: str) -> Category | None: ...
    async def get_all(self) -> list[Category]: ...
    async def get_by_group_id(self, group_id: UUID) -> list[Category]: ...
    async def save(self, entity: Category) -> Category: ...
    async def save_batch(self, entities: list[Category]) -> list[Category]: ...
    async def count(self) -> int: ...
    async def get_unmapped(self) -> list[Category]: ...
    async def unmap_by_group_id(self, group_id: UUID) -> int: ...
