from typing import Protocol
from uuid import UUID

from src.domain.entities.category_mapping import CategoryMapping


class CategoryMappingRepositoryProtocol(Protocol):
    async def get_by_category(self, category: str) -> CategoryMapping | None: ...
    async def get_all(self) -> list[CategoryMapping]: ...
    async def get_by_group_id(self, group_id: UUID) -> list[CategoryMapping]: ...
    async def save(self, entity: CategoryMapping) -> CategoryMapping: ...
    async def save_batch(
        self, entities: list[CategoryMapping]
    ) -> list[CategoryMapping]: ...
    async def count(self) -> int: ...
