from typing import Protocol
from uuid import UUID

from src.domain.entities.category_group import CategoryGroup


class CategoryGroupRepositoryProtocol(Protocol):
    async def get_by_id(self, id: UUID) -> CategoryGroup | None: ...
    async def get_all(self) -> list[CategoryGroup]: ...
    async def save(self, entity: CategoryGroup) -> CategoryGroup: ...
    async def save_batch(
        self, entities: list[CategoryGroup]
    ) -> list[CategoryGroup]: ...
    async def count(self) -> int: ...
    async def delete(self, id: UUID) -> bool: ...
