from typing import Protocol
from uuid import UUID

from src.domain.entities.person import Person


class PersonRepositoryProtocol(Protocol):
    async def get_by_id(self, id: UUID) -> Person | None: ...
    async def get_all(self) -> list[Person]: ...
    async def save(self, entity: Person) -> Person: ...
    async def save_batch(self, entities: list[Person]) -> list[Person]: ...
