from typing import Protocol
from uuid import UUID

from src.domain.entities.settlement import Settlement


class SettlementRepositoryProtocol(Protocol):
    async def get_by_id(self, id: UUID) -> Settlement | None: ...
    async def get_by_period(self, year: int, month: int) -> list[Settlement]: ...
    # All-time fetch for the settlement ledger. No ordering guarantee —
    # the ledger sorts payments chronologically itself.
    async def get_all(self) -> list[Settlement]: ...
    async def save(self, entity: Settlement) -> Settlement: ...
    async def delete(self, id: UUID) -> bool: ...
