from typing import Protocol
from uuid import UUID

from src.domain.entities.settlement import Settlement


class SettlementRepositoryProtocol(Protocol):
    async def get_by_id(self, id: UUID) -> Settlement | None: ...
    async def get_by_period(self, year: int, month: int) -> list[Settlement]: ...
    async def get_by_year(self, year: int) -> list[Settlement]: ...
    async def save(self, entity: Settlement) -> Settlement: ...
    async def delete(self, id: UUID) -> bool: ...
