from typing import Protocol
from uuid import UUID

from src.domain.entities.settlement_merchant import SettlementMerchant


class SettlementMerchantRepositoryProtocol(Protocol):
    async def get_by_id(self, id: UUID) -> SettlementMerchant | None: ...
    async def get_all(self) -> list[SettlementMerchant]: ...
    async def save(self, entity: SettlementMerchant) -> SettlementMerchant: ...
    async def save_batch(
        self, entities: list[SettlementMerchant]
    ) -> list[SettlementMerchant]: ...
    async def delete(self, id: UUID) -> bool: ...
    async def count(self) -> int: ...
