from datetime import date
from typing import Protocol
from uuid import UUID

from src.domain.entities.transaction import Transaction


class TransactionRepositoryProtocol(Protocol):
    async def get_by_id(self, id: UUID) -> Transaction | None: ...
    async def get_by_ids(self, ids: list[UUID]) -> list[Transaction]: ...
    async def get_household_by_period(
        self, year: int, month: int
    ) -> list[Transaction]: ...
    async def get_household_by_year(self, year: int) -> list[Transaction]: ...
    async def get_by_year(self, year: int) -> list[Transaction]: ...
    async def get_household_by_date_range(
        self,
        start_date: date,
        end_date: date,
        *,
        tags: tuple[str, ...] | None = None,
    ) -> list[Transaction]: ...
    async def get_by_person_and_date_range(
        self,
        person_id: UUID,
        start_date: date,
        end_date: date,
        *,
        tags: tuple[str, ...] | None = None,
    ) -> list[Transaction]: ...
    async def save(self, entity: Transaction) -> Transaction: ...
    async def save_batch(self, entities: list[Transaction]) -> list[Transaction]: ...
    async def update_mutable_fields(self, entity: Transaction) -> Transaction: ...
    async def update_all_fields(self, entity: Transaction) -> Transaction: ...
    async def get_latest_household_transaction_date(self) -> date | None: ...
    async def get_distinct_tags(self) -> list[str]: ...
