from datetime import date
from typing import Protocol
from uuid import UUID

from src.domain.entities.transaction import Transaction


class TransactionRepositoryProtocol(Protocol):
    async def get_by_id(self, id: UUID) -> Transaction | None: ...
    async def get_by_upload_id(self, upload_id: UUID) -> list[Transaction]: ...
    async def get_shared_by_period(
        self, year: int, month: int
    ) -> list[Transaction]: ...
    async def get_by_person_and_date_range(
        self, person_id: UUID, start_date: date, end_date: date
    ) -> list[Transaction]: ...
    async def save(self, entity: Transaction) -> Transaction: ...
    async def save_batch(self, entities: list[Transaction]) -> list[Transaction]: ...
    async def update_mutable_fields(self, entity: Transaction) -> Transaction: ...
    async def delete_by_upload_id(self, upload_id: UUID) -> int: ...
    async def get_distinct_categories(self) -> list[str]: ...
